def test_good_teaching_script_passes():
    ...

def test_empty_script_fails():
    ...

def test_short_script_fails():
    ...

def test_placeholder_text_fails():
    ...

def test_ai_meta_text_fails():
    ...

def test_script_without_example_fails():
    ...

def test_script_without_conclusion_fails():
    ...